# Generated by Django 5.2.4 on 2026-09-09 12:51

import django.db.models.deletion
import submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_code_path', models.FileField(upload_to=submissions.models.submission_code_path)),
                ('lang', models.CharField(max_length=50)),
                ('verdict', models.CharField(choices=[('Pending', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='Pending', max_length=20)),
                ('max_time_ms', models.IntegerField(blank=True, null=True)),
                ('max_memory_kb', models.IntegerField(blank=True, null=True)),
                ('failed_testcase_sequence', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('Pending', 'Pending'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], default='Pending', max_length=20)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('execution_mem_kb', models.IntegerField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_results', to='submissions.submission')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_results', to='problems.testcase')),
            ],
            options={
                'ordering': ['testcase__sequence_number'],
            },
        ),
    ]
