# Generated by Django 5.2.17 on 2026-09-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='author',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='authorDetails',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
