# Generated by Django 5.2.4 on 2026-09-09 12:51

import django.db.models.deletion
import problems.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('inputs_format', models.TextField()),
                ('output_format', models.TextField()),
                ('constraints_text', models.TextField()),
                ('time_limit_ms', models.FloatField()),
                ('memory_limit_mb', models.IntegerField()),
                ('checker_type', models.CharField(choices=[('standard', 'Standard Token Matcher'), ('custom', 'Custom Checker')], default='standard', max_length=50)),
                ('checker_file_path', models.FileField(blank=True, null=True, upload_to='checkers/')),
                ('checker_lang', models.CharField(blank=True, help_text='e.g., cpp, python', max_length=50, null=True)),
                ('difficulty_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('input_file_path', models.FileField(upload_to=problems.models.testcase_input_path)),
                ('output_file_path', models.FileField(upload_to=problems.models.testcase_output_path)),
                ('is_sample', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem')),
            ],
            options={
                'ordering': ['problem', 'sequence_number'],
                'unique_together': {('problem', 'sequence_number')},
            },
        ),
    ]
