# Generated by Django 5.2.4 on 2026-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Solved_Problems_Counter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
